# Generated by Django 4.2.13 on 2025-04-04 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crawling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('stock_code', models.TextField()),
                ('comment', models.TextField()),
                ('save_at', models.DateField()),
            ],
        ),
    ]
